# Generated by Django 4.0.2 on 2022-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('photo_url', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
